name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: npm ci
    - name: Truffle - compile
      run: npx truffle compile
    - name: Truffle - test
      run: npx truffle test --stacktrace
    - name: Frontend - Clean and build
      run: npm run build
    - name: Frontend - Tests
      run: npm test

      #deploy-frontend:
      #runs-on: ubuntu-latest
      #steps:
