name: Build, Test, (Publish)

on: [push, pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Forge Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
      - uses: actions/upload-artifact@v3
        with:
          name: json-abi
          path: out/
          retention-days: 1


  generate-types:
    name: Generate TypeScript Types
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/download-artifact@v3
        with:
          name: json-abi
          path: out/

      - uses: actions/setup-node@v3
        name: Install Node
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - run: pnpm install --frozen-lockfile
        name: Install Dependencies

      - run: pnpm run generate-types
        name: Generate TypeScript Types

      - uses: actions/upload-artifact@v3
        with:
          name: ts-types
          path: types/
          retention-days: 1

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [build-test, generate-types]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/download-artifact@v3
        with:
          name: ts-types
          path: types/

      - uses: actions/setup-node@v3
        name: Install Node
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - run: pnpm install --frozen-lockfile
        name: Install Dependencies

      - run: pnpm pack
        name: Install Dependencies

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          files: |
            createz-contracts-*.tgz
            README.md
            LICENSE

      - run: pnpm publish --tag ${NPM_TAG} --no-git-checks
        name: Publish to NPM Registry
        env:
          NPM_TAG: ${{ (contains(github.ref, 'alpha') || contains(github.ref, 'beta')) && 'next' || 'latest' }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
